HSB/Controllers/CasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HSB.Models;
using Microsoft.AspNetCore.Authorization;
using HSB.Repositories.Interfaces;

namespace HSB.Controllers
{
    [Authorize]
    public class CasesController : Controller
    {
        private readonly ICaseRepository _repository;

        public CasesController(ICaseRepository repository)
        {
            _repository = repository;
        }

        // GET: Members
        public async Task<IActionResult> Index()
        {
            return View(await _repository.GetCasesAsync(true));
        }

        public async Task<IActionResult> PassiveCases()
        {
            var cases = await _repository.GetCasesAsync(false); 
            return View(cases);
          
        }
        // GET: Members/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            var myCase = await _repository.GetByIdAsync(id);
            if (myCase == null) return NotFound();
            return View(myCase);
        }

        // GET: Members/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] Case myCase)
        {
            if (ModelState.IsValid)
            {
                await _repository.CreateCaseAsync(myCase);
                return RedirectToAction(nameof(Index));
            }
            return View(myCase);
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
          
            var myCase = await _repository.GetByIdAsync(id);
            if (myCase == null)
            {
                return NotFound();
            }
            return View(myCase);
        }

        // POST: Members/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, [FromForm] Case myCase)
        {
            if (id != myCase.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   await  _repository.UpdateCaseAsync(myCase);
                }
                catch (DbUpdateConcurrencyException e)
                {
                    throw e;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(myCase);
        }

        // GET: Members/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
           
            var myCase = await _repository.GetByIdAsync(id);
            if (myCase == null)
            {
                return NotFound();
            }

            return View(myCase);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _repository.DeleteCaseAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

HSB/Controllers/DonorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HSB.Models;
using HSB.Repositories.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace HSB.Controllers
{
    [Authorize]
    public class DonorsController : Controller
    {
        private readonly IDonorRepository _repository;

        public DonorsController(IDonorRepository repository)
        {
            _repository = repository;
        }

        // GET: Donors
        public async Task<IActionResult> Index()
        {
            return View(await _repository.GetDonorsAsync());
        }

        // GET: Donors/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            var donor = await _repository.GetByIdAsync(id);
            if (donor == null) return NotFound();
            return View(donor);
        }

        // GET: Donors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Donors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] Donor donor)
        {
            if (ModelState.IsValid)
            {
                await _repository.CreateDonorAsync(donor);
                return RedirectToAction(nameof(Index));
            }
            return View(donor);
        }

        // GET: Donors/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var donor = await _repository.GetByIdAsync(id);
            if (donor == null)
            {
                return NotFound();
            }
            return View(donor);
        }

        // POST: Donors/Edit/5
        [HttpPost]
       
        public async Task<IActionResult> Edit(Guid id, [FromForm] Donor donor)
        {
            if (id != donor.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await  _repository.UpdateDonorAsync(donor);
                }
                catch (DbUpdateConcurrencyException e)
                {
                    throw e;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(donor);
        }

        // GET: Donors/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            var donor = await _repository.GetByIdAsync(id);
            if (donor == null)
            {
                return NotFound();
            }

            return View(donor);
        }

        // POST: Donors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _repository.DeleteDonorAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

HSB/Controllers/MembersController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HSB.Models;
using HSB.Repositories;
using Microsoft.AspNetCore.Authorization;
using HSB.Repositories.Interfaces;
using HSB.Services;
using System.Collections.Generic;

namespace HSB.Controllers
{
    [Authorize]
    public class MembersController : Controller
    {
        private readonly IMemberRepository _repository;
        private readonly IExportDataService<Member> _exportDataService;

        public MembersController(IMemberRepository repository, IExportDataService<Member> exportDataService)
        {
            _repository = repository;
            _exportDataService = exportDataService;
        }

        // GET: Members
        public async Task<IActionResult> Index()
        {
            return View(await _repository.GetMembersAsync(true));
        }

        public async Task<IActionResult> PassiveMembers()
        {
            var members = await _repository.GetMembersAsync(false); 
            return View(members);
          
        }
        // GET: Members/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            var member = await _repository.GetByIdAsync(id);
            if (member == null) return NotFound();
            return View(member);
        }

        // GET: Members/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Members/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] Member member)
        {
            if (ModelState.IsValid)
            {
                await _repository.CreateMemberAsync(member);
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
          
            var member = await _repository.GetByIdAsync(id);
            if (member == null)
            {
                return NotFound();
            }
            return View(member);
        }

        // POST: Members/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, [FromForm] Member member)
        {
            if (id != member.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   await  _repository.UpdateMemberAsync(member);
                }
                catch (DbUpdateConcurrencyException e)
                {
                    throw e;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(member);
        }

        // GET: Members/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(Guid id)
        {
           
            var member = await _repository.GetByIdAsync(id);
            if (member == null)
            {
                return NotFound();
            }

            return View(member);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _repository.DeleteMemberAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<ActionResult> CreateCmsFile()
        {
            var _listOfMembers = await _repository.GetMembersAsync(true);

            IEnumerable<Member> listOfMembers = new List<Member>(_listOfMembers);
            byte[] mem = _exportDataService.CreateMembersFile(listOfMembers);
            

            return File(mem, "text/csv", "Export.csv");
        }
    }
}

HSB/Controllers/StoriesController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HSB.Models;
using Microsoft.AspNetCore.Authorization;
using HSB.Repositories.Interfaces;
using Microsoft.AspNetCore.Http;
using HSB.Services;

namespace HSB.Controllers
{
    [Authorize]
    public class StoriesController : Controller
    {
         private readonly IStoryRepository _repository;
         private readonly IImageService _imageService;

        public StoriesController(IStoryRepository repository, IImageService imageService)
        {
            _repository = repository;
            _imageService = imageService;
        }

        // GET:  Stories
        public async Task<IActionResult> Index()
        {
            return View(await _repository.GetStoriesAsync());
        }

        // GET:  Stories/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            var story = await _repository.GetByIdAsync(id);
            if (story == null) return NotFound();
            return View(story);
        }

        // GET:  Stories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST:  Stories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create([FromForm] Story story, IFormFile image)
        {
            story.ImagePath = await _imageService.UploadImage(story, image);
            ModelState.Remove("ID");
            if (ModelState.IsValid)
            {
                await _repository.CreateStoryAsync(story);
                return RedirectToAction(nameof(Index));
            }
            return View(story);
        }

        // GET:  Stories/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
          
            var story = await _repository.GetByIdAsync(id);
            if (story == null) return NotFound();
            
            return View(story);
        }

        // POST:  Stories/Edit/5
        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, [FromForm] Story story, IFormFile newImage)
        {
            if (id != story.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   await  _repository.UpdateStoryAsync(story);
                }
                catch (DbUpdateConcurrencyException e)
                {
                    throw e;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(story);
        }

        // GET:  Stories/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
           
            var story = await _repository.GetByIdAsync(id);
            if (story == null) return NotFound();
             return View(story);
        }

        // POST: Stories/Delete/5
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(Guid id, string imagePath)
        {
            await  _imageService.DeleteImage(imagePath);
            await _repository.DeleteStoryAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("DeleteImage")]
        public async Task<IActionResult> DeleteImage(string imagePath)
        {
            await _imageService.DeleteImage(imagePath);
            //fortsætte herfra
            return LocalRedirect(nameof(Edit));
        }
    }
}

HSB/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title></title>

    <!-- Bootstrap core CSS -->
    <link href="~/HomePage/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="~/HomePage/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="~/HomePage/css/clean-blog.min.css" rel="stylesheet">

</head>

<body style="background-color:rgb(190, 255, 213)">
    <header>
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                @*<a class="navbar-brand" href="index.html">Start Bootstrap</a>*@
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/lib/Ico/HSB_logo.png" width="60" height="45" alt="ico" style="margin-right: 50px"></img></a>

                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                      
                        <li class="nav-item">
                            <a class="navbar-brand" asp-controller="Home" asp-action="AddMember">Bliv Medlem</a>
                        <li />

                        <li class="nav-item">
                            <a class="navbar-brand" asp-controller="Home" asp-action="AddCase">Ansøg om hjælp</a>
                        <li />
                    </ul>
                </div>
            </div>
        </nav>

        <!-- Page Header -->
        <header class="masthead">
            <div class="overlay" style="background-image: url('HomePage/img/86924_1.jpg'); background-size: contain;"></div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto">
                        <div class="site-heading">
                             <h1>Hjælp Syge Børn</h1>
                            <span class="subheading">Donec congue nibh eleifend convallis ornare. 
                                Duis id est mollis, ornare neque a, egestas metus. Quisque id placerat odio. 
                                Maecenas et pellentesque tortor. Duis nibh est, viverra in elit at, scelerisque 
                                dapibus arcj. </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </header>


    <!-- Main Content -->
    <div class="container">
        @RenderBody()
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">


                @*</div>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Man must explore, and this is exploration at its greatest
                        </h2>
                        <h3 class="post-subtitle">
                            Problems look mighty small from 150 miles up
                        </h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#">Start Bootstrap</a>
                        on September 24, 2019
                    </p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            I believe every human has a finite number of heartbeats. I don't intend to waste any of mine.
                        </h2>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#">Start Bootstrap</a>
                        on September 18, 2019
                    </p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Science has not yet mastered prophecy
                        </h2>
                        <h3 class="post-subtitle">
                            We predict too much for the next year and yet far too little for the next ten.
                        </h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#">Start Bootstrap</a>
                        on August 24, 2019
                    </p>
                </div>
                <hr>
                <div class="post-preview">
                    <a href="post.html">
                        <h2 class="post-title">
                            Failure is not an option
                        </h2>
                        <h3 class="post-subtitle">
                            Many say exploration is part of our destiny, but it’s actually our duty to future generations.
                        </h3>
                    </a>
                    <p class="post-meta">
                        Posted by
                        <a href="#">Start Bootstrap</a>
                        on July 8, 2019
                    </p>
                </div>
                <hr>*@
                <!-- Pager -->
                @*<div class="clearfix">
                    <a class="btn btn-primary float-right" href="#">Older Posts &rarr;</a>
                </div>*@
            </div>
        </div>
    </div>
    

<!-- Footer -->
<footer style="background:antiquewhite">
    <div class="container">
        <div class="row" >

                 @*<div class="col-1"></div>*@
            <div class="col-3" >
              
                    
                        <a  asp-controller="Home" asp-action="AddDonor">Reg CPR-nummer</a>
                    <br/>

                     <a asp-area="Identity" asp-page="/Account/Login">Administrere</a>
                    <br/>
                    
                        <a href="#">Kontakt os</a>
                    <br/>
                   <a href="#">Om HSB</a>
             </div>
            <div class="col-2"></div>
                 <div class="col-2">
                     <br/>
                     <div style="margin-top: 50px">
                         <a target="_blank" href="https://www.facebook.com/groups/588009374579563/">
                             <span class="fa-stack fa-lg">
                                 <i class="fas fa-circle fa-stack-2x"></i>
                                 <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                             </span>
                         </a>

                     </div>
                 </div>
                 <div class="col-1"></div>
                 <div class="col-3" >
                     <img src="../HomePage/img/mobilePay-logo.jpg" width="200" height="160" alt="ico" ></img>
                     <br/>
                     <div style="padding-top: 30px"></div>
                     <button type="button" onclick="alert('Pay 50kr')"  style="background:darksalmon; border-radius: 0 10px;">50 kr</button>
                     <button type="button" onclick="alert('Pay 75kr')"  style="background: darksalmon; border-radius: 0 10px;">75s kr</button>
                     <button type="button" onclick="alert('Pay 100kr')" style="background: darksalmon; border-radius: 0 10px;">100 kr</button>
                 </div>


        </div> 
        <p class="copyright text-muted">Hjælp Syge Børn 2019</p>
    </div>

</footer>   @*<div class="container">*@
            @*<li class="nav-item">
            
            <li />
            <li class="nav-item">
              
                </li>
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto">
                        
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a class="navbar-brand" asp-controller="Home" asp-action="AddDonor">Reg CPR-nummer</a>
                            </li>
                            
                            <li class="list-inline-item">
                                <a class="navbar-brand" asp-area="Identity" asp-page="/Account/Login">Administrere</a>
                            </li>
                            
                            <li class="list-inline-item">
                                <a target="_blank" href="https://www.facebook.com/groups/588009374579563/">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>

                        </ul>
                        <p class="copyright text-muted">Hjælp Syge Børn 2019</p>
                    </div>
                </div>
</div>*@
   

    <!-- Bootstrap core JavaScript -->
    <script src="~/HomePage/vendor/jquery/jquery.min.js"></script>
    <script src="~/HomePage/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="~/HomePage/js/clean-blog.min.js"></script>

</body>

</html>

HSB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hjælp Syge Børn</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-Superhero.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-Superhero.css" />

    </environment>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-Superhero.css" />

    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="icon" href="~/favicon.ico">
</head>
<body>

    <ul class="navbar-nav"></ul>





    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">

            <div class="container">

                <a class="navbar-brand"><img src="~/lib/Ico/HSB_logo.png" width="50" height="35" alt="ico" style="margin-right: 50px"></img></a>
                <a class="navbar-brand" asp-area="" asp-controller="Members" asp-action="Index">Medlemmer </a>
                <a class="navbar-brand" asp-controller="Donors" asp-action="Index">Donorer</a>
                <a class="navbar-brand" asp-controller="Cases" asp-action="Index">Børn</a>
                <a class="navbar-brand" asp-controller="Stories" asp-action="Index" style="margin-right: 350px">Historier</a>
              <partial name="_LoginPartial" />

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            @*<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>*@
                        </li>
                        <li class="nav-item">
                            @*<a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    @*<header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HSB</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Hjælp Syge Børn 
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>